### ISSUE TITLE
Switch to custom node pool

### ISSUE THREAD

**Issue by jmelot** [georgetown-cset/huggingface-etl#4]
I should have noticed this during code review but just did - you're using the default node pool that cloud composer is running in here:

https://github.com/georgetown-cset/huggingface-etl/blob/main/huggingface_dag.py#L126
https://github.com/georgetown-cset/huggingface-etl/blob/main/huggingface_dag.py#L189

I see you've already created a custom node pool within this cluster, so you should be able to just switch to that one (`huggingface-pool`)

**Comment by rggelles** [comment]
I was under the impression it was okay to use the default pool if I didn't need anything fancier! But I will switch over; I don't think it should harm anything.
